version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - JWT_SECRET=your_super_secret_jwt_key_here_make_it_long_and_complex
      - ENVIRONMENT=development
      - PORT=8080
    depends_on:
      - mongo
    networks:
      - ngobrolyuk-network
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ngobrolyuk
    volumes:
      - mongo-data:/data/db
    networks:
      - ngobrolyuk-network
volumes:
  mongo-data:
networks:
  ngobrolyuk-network:
    driver: bridge